### ISSUE TITLE
Restructure branches to reflect what we present in paper

### ISSUE THREAD

**Issue by arnfinn** [PCMSolver/pcmsolver#154]
We will use [this branching model](http://www.bitsnbites.eu/a-stable-mainline-branching-model-for-git/
). Thus:
- all development happens on the `master` branch.
- for every minor release `X.Y`, a new branch is created named `release/X.Y`.
- the release branches will never be merged back into `master`.
- bug fixes will be cherry picked from `master` to `release/X.Y`.
- all tags are on release branches.

## Tasks
These tasks have to be done, while keeping all the tags.
- [x] Rename `release/1.2.Z` to `master`
  - Unprotect `master`
  - `git push -f origin/upstream/whatever master` while on `release/1.2.Z`
- [x] Rename `release/1.Y` to `release/1.1`
  - `git push -u origin/upstream/whatever release/1.1` while on `release/1.Y`
- [x] Create `release/1.2`
- [x] Protect `master`, `release/1.1` and `release/1.2`

**Comment by arnfinn** [comment]
How can we keep the tags on the two release branches?

- The `release/1.2` branch has to be created from the tag `v1.2.0-rc1` commit
- Is all the `v1.1`-tags on the `release/1.Y` branch? Then I assume the tags will also be on the `release/1.1` branch after renaming?

**Comment by robertodr** [comment]
I agree with this plan, though we might have to experiment a bit on some test repositories to iron out the sequence of commands to perform.
Some thoughts, a bit at random:
- The `git branch --move <new_name>` followed by a `git push -u -f` achieves renaming keeping the whole reflog. I think this is what we want.
- It might be easier if we just delete the superstale `master` altogether, before starting with the renaming. 
- All `v1.1` tags should be on `release/1.Y`. But I do not know how to check that that's actually true. 
- To make things look clean (since we are at it) I suggest:
   - We _delete_ the `v1.2.0-rc1` tag
   - Rename `release/1.2.Z` to `master`
   - Go back to [this commit](https://github.com/PCMSolver/pcmsolver/commit/022f7614ff6a78e39232d693dd82112f374e5101) and branch off `release/1.2`
   - On `release/1.2` replay the immediate next commit and re-tag `v1.2.0-rc1`
   - From there to the actual 1.2.0 we will cheat and cherry-pick the commits that are now on `master`

**Comment by bast** [comment]
I need to read this tomorrow with a nice coffee and think about it for a moment - I will comment soon.

**Comment by robertodr** [comment]
Yes, we'll definitely play around with forks :)

**Comment by bast** [comment]
Answering some questions:

Git indeed does not care which way you cherry pick.

A tag points to a commit, very much like a branch - in contrast to a branch it does not move. A tag can point to a commit which is accessible from many branches. Then you can say that the tag is accessible (or "belongs to") many branches.

"All v1.1 tags should be on release/1.Y" - yes they are:
```
$ git checkout release/1.Y

$ git tag --merged
v1.1.0
v1.1.1
v1.1.10
v1.1.11
v1.1.12
v1.1.2
v1.1.3
v1.1.4
v1.1.5
v1.1.6
v1.1.7
v1.1.8
v1.1.9

$ git tag --no-merged
v1.2.0-rc1
```

**Comment by arnfinn** [comment]
Did the following on a fresh clone of `pcmsolverplayground/pcmsolver`:

```
git co release/1.Y
git push origin --delete release/1.Y
git branch --move release/1.1
git push -u -f origin release/1.1:release/1.1
git co release/1.2.Z
git branch --move release/1.2
git push origin --delete release/1.2.Z
git push -u -f origin release/1.2:release/1.2
git co -b master
git push -u origin master
```

**Comment by bast** [comment]
Before pushing changes I recommend to mirror entire repo under different name to the same org, e.g. `PCMSolver/pcmsolver-backup`:
```
git clone --mirror github.com:PCMSolver/pcmsolver.git
cd pcmsolver.git
git push --mirror github.com:PCMSolver/pcmsolver-backup.git
```

**Comment by arnfinn** [comment]
Did as you wrote and got some warnings and errors. Still OK? Repository is here: https://github.com/PCMSolver/pcmsolver-backup
```
$ git push --mirror git@github.com:PCMSolver/pcmsolver-backup.git
Counting objects: 25852, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (6730/6730), done.
Writing objects: 100% (25852/25852), 236.30 MiB | 2.31 MiB/s, done.
Total 25852 (delta 18943), reused 25852 (delta 18943)
remote: Resolving deltas: 100% (18943/18943), done.
remote: warning: GH001: Large files detected. You may want to try Git Large File Storage - https://git-lfs.github.com.
remote: warning: See http://git.io/iEPt8g for more information.
remote: warning: File cmake/downloaded/boost_1_54_0.zip is 98.40 MB; this is larger than GitHub's recommended maximum file size of 50.00 MB
remote: warning: File external/boost_1_54_0.tar.gz is 66.04 MB; this is larger than GitHub's recommended maximum file size of 50.00 MB
remote: warning: File external/boost_1_55_0.tar.gz is 66.26 MB; this is larger than GitHub's recommended maximum file size of 50.00 MB
To github.com:PCMSolver/pcmsolver-backup.git
 * [new branch]        conda-throwaway -> conda-throwaway
 * [new branch]        coverity_scan -> coverity_scan
 * [new branch]        master -> master
 * [new branch]        release/1.2.Z -> release/1.2.Z
 * [new branch]        release/1.Y -> release/1.Y
 * [new branch]        robertodr-patch-1 -> robertodr-patch-1
 * [new tag]           v1.1.0 -> v1.1.0
 * [new tag]           v1.1.1 -> v1.1.1
 * [new tag]           v1.1.10 -> v1.1.10
 * [new tag]           v1.1.11 -> v1.1.11
 * [new tag]           v1.1.12 -> v1.1.12
 * [new tag]           v1.1.2 -> v1.1.2
 * [new tag]           v1.1.3 -> v1.1.3
 * [new tag]           v1.1.4 -> v1.1.4
 * [new tag]           v1.1.5 -> v1.1.5
 * [new tag]           v1.1.6 -> v1.1.6
 * [new tag]           v1.1.7 -> v1.1.7
 * [new tag]           v1.1.8 -> v1.1.8
 * [new tag]           v1.1.9 -> v1.1.9
 * [new tag]           v1.2.0-rc1 -> v1.2.0-rc1
 ! [remote rejected]   refs/pull/1/head -> refs/pull/1/head (deny updating a hidden ref)
 ! [remote rejected]   refs/pull/101/head -> refs/pull/101/head (deny updating a hidden ref)
 ! [remote rejected]   refs/pull/102/head -> refs/pull/102/head (deny updating a hidden ref)
 ! [remote rejected]   refs/pull/103/head -> refs/pull/103/head (deny updating a hidden ref)
 ! [remote rejected]   refs/pull/104/head -> refs/pull/104/head (deny updating a hidden ref)
 ! [remote rejected]   refs/pull/105/head -> refs/pull/105/head (deny updating a hidden ref)
 ! [remote rejected]   refs/pull/105/merge -> refs/pull/105/merge (deny updating a hidden ref)
 ! [remote rejected]   refs/pull/107/head -> refs/pull/107/head (deny updating a hidden ref)
 ! [remote rejected]   refs/pull/109/head -> refs/pull/109/head (deny updating a hidden ref)
 ! [remote rejected]   refs/pull/110/head -> refs/pull/110/head (deny updating a hidden ref)
 ! [remote rejected]   refs/pull/113/head -> refs/pull/113/head (deny updating a hidden ref)
 ! [remote rejected]   refs/pull/114/head -> refs/pull/114/head (deny updating a hidden ref)
 ! [remote rejected]   refs/pull/115/head -> refs/pull/115/head (deny updating a hidden ref)
 ! [remote rejected]   refs/pull/117/head -> refs/pull/117/head (deny updating a hidden ref)
 ! [remote rejected]   refs/pull/118/head -> refs/pull/118/head (deny updating a hidden ref)
 ! [remote rejected]   refs/pull/119/head -> refs/pull/119/head (deny updating a hidden ref)
 ! [remote rejected]   refs/pull/121/head -> refs/pull/121/head (deny updating a hidden ref)
 ! [remote rejected]   refs/pull/122/head -> refs/pull/122/head (deny updating a hidden ref)
 ! [remote rejected]   refs/pull/123/head -> refs/pull/123/head (deny updating a hidden ref)
 ! [remote rejected]   refs/pull/128/head -> refs/pull/128/head (deny updating a hidden ref)
 ! [remote rejected]   refs/pull/129/head -> refs/pull/129/head (deny updating a hidden ref)
 ! [remote rejected]   refs/pull/129/merge -> refs/pull/129/merge (deny updating a hidden ref)
 ! [remote rejected]   refs/pull/130/head -> refs/pull/130/head (deny updating a hidden ref)
 ! [remote rejected]   refs/pull/130/merge -> refs/pull/130/merge (deny updating a hidden ref)
 ! [remote rejected]   refs/pull/131/head -> refs/pull/131/head (deny updating a hidden ref)
 ! [remote rejected]   refs/pull/132/head -> refs/pull/132/head (deny updating a hidden ref)
 ! [remote rejected]   refs/pull/133/head -> refs/pull/133/head (deny updating a hidden ref)
 ! [remote rejected]   refs/pull/134/head -> refs/pull/134/head (deny updating a hidden ref)
 ! [remote rejected]   refs/pull/135/head -> refs/pull/135/head (deny updating a hidden ref)
 ! [remote rejected]   refs/pull/135/merge -> refs/pull/135/merge (deny updating a hidden ref)
 ! [remote rejected]   refs/pull/136/head -> refs/pull/136/head (deny updating a hidden ref)
 ! [remote rejected]   refs/pull/138/head -> refs/pull/138/head (deny updating a hidden ref)
 ! [remote rejected]   refs/pull/138/merge -> refs/pull/138/merge (deny updating a hidden ref)
 ! [remote rejected]   refs/pull/140/head -> refs/pull/140/head (deny updating a hidden ref)
 ! [remote rejected]   refs/pull/140/merge -> refs/pull/140/merge (deny updating a hidden ref)
 ! [remote rejected]   refs/pull/141/head -> refs/pull/141/head (deny updating a hidden ref)
 ! [remote rejected]   refs/pull/142/head -> refs/pull/142/head (deny updating a hidden ref)
 ! [remote rejected]   refs/pull/143/head -> refs/pull/143/head (deny updating a hidden ref)
 ! [remote rejected]   refs/pull/145/head -> refs/pull/145/head (deny updating a hidden ref)
 ! [remote rejected]   refs/pull/145/merge -> refs/pull/145/merge (deny updating a hidden ref)
 ! [remote rejected]   refs/pull/146/head -> refs/pull/146/head (deny updating a hidden ref)
 ! [remote rejected]   refs/pull/149/head -> refs/pull/149/head (deny updating a hidden ref)
 ! [remote rejected]   refs/pull/150/head -> refs/pull/150/head (deny updating a hidden ref)
 ! [remote rejected]   refs/pull/151/head -> refs/pull/151/head (deny updating a hidden ref)
 ! [remote rejected]   refs/pull/152/head -> refs/pull/152/head (deny updating a hidden ref)
 ! [remote rejected]   refs/pull/153/head -> refs/pull/153/head (deny updating a hidden ref)
 ! [remote rejected]   refs/pull/155/head -> refs/pull/155/head (deny updating a hidden ref)
 ! [remote rejected]   refs/pull/156/head -> refs/pull/156/head (deny updating a hidden ref)
 ! [remote rejected]   refs/pull/158/head -> refs/pull/158/head (deny updating a hidden ref)
 ! [remote rejected]   refs/pull/17/head -> refs/pull/17/head (deny updating a hidden ref)
 ! [remote rejected]   refs/pull/20/head -> refs/pull/20/head (deny updating a hidden ref)
 ! [remote rejected]   refs/pull/3/head -> refs/pull/3/head (deny updating a hidden ref)
 ! [remote rejected]   refs/pull/31/head -> refs/pull/31/head (deny updating a hidden ref)
 ! [remote rejected]   refs/pull/31/merge -> refs/pull/31/merge (deny updating a hidden ref)
 ! [remote rejected]   refs/pull/38/head -> refs/pull/38/head (deny updating a hidden ref)
 ! [remote rejected]   refs/pull/5/head -> refs/pull/5/head (deny updating a hidden ref)
 ! [remote rejected]   refs/pull/6/head -> refs/pull/6/head (deny updating a hidden ref)
 ! [remote rejected]   refs/pull/60/head -> refs/pull/60/head (deny updating a hidden ref)
 ! [remote rejected]   refs/pull/64/head -> refs/pull/64/head (deny updating a hidden ref)
 ! [remote rejected]   refs/pull/65/head -> refs/pull/65/head (deny updating a hidden ref)
 ! [remote rejected]   refs/pull/65/merge -> refs/pull/65/merge (deny updating a hidden ref)
 ! [remote rejected]   refs/pull/67/head -> refs/pull/67/head (deny updating a hidden ref)
 ! [remote rejected]   refs/pull/68/head -> refs/pull/68/head (deny updating a hidden ref)
 ! [remote rejected]   refs/pull/71/head -> refs/pull/71/head (deny updating a hidden ref)
 ! [remote rejected]   refs/pull/72/head -> refs/pull/72/head (deny updating a hidden ref)
 ! [remote rejected]   refs/pull/73/head -> refs/pull/73/head (deny updating a hidden ref)
 ! [remote rejected]   refs/pull/74/head -> refs/pull/74/head (deny updating a hidden ref)
 ! [remote rejected]   refs/pull/77/head -> refs/pull/77/head (deny updating a hidden ref)
 ! [remote rejected]   refs/pull/80/head -> refs/pull/80/head (deny updating a hidden ref)
 ! [remote rejected]   refs/pull/80/merge -> refs/pull/80/merge (deny updating a hidden ref)
 ! [remote rejected]   refs/pull/81/head -> refs/pull/81/head (deny updating a hidden ref)
 ! [remote rejected]   refs/pull/81/merge -> refs/pull/81/merge (deny updating a hidden ref)
 ! [remote rejected]   refs/pull/82/head -> refs/pull/82/head (deny updating a hidden ref)
 ! [remote rejected]   refs/pull/83/head -> refs/pull/83/head (deny updating a hidden ref)
 ! [remote rejected]   refs/pull/85/head -> refs/pull/85/head (deny updating a hidden ref)
 ! [remote rejected]   refs/pull/86/head -> refs/pull/86/head (deny updating a hidden ref)
 ! [remote rejected]   refs/pull/87/head -> refs/pull/87/head (deny updating a hidden ref)
 ! [remote rejected]   refs/pull/87/merge -> refs/pull/87/merge (deny updating a hidden ref)
 ! [remote rejected]   refs/pull/89/head -> refs/pull/89/head (deny updating a hidden ref)
 ! [remote rejected]   refs/pull/92/head -> refs/pull/92/head (deny updating a hidden ref)
 ! [remote rejected]   refs/pull/92/merge -> refs/pull/92/merge (deny updating a hidden ref)
 ! [remote rejected]   refs/pull/93/head -> refs/pull/93/head (deny updating a hidden ref)
 ! [remote rejected]   refs/pull/94/head -> refs/pull/94/head (deny updating a hidden ref)
 ! [remote rejected]   refs/pull/94/merge -> refs/pull/94/merge (deny updating a hidden ref)
 ! [remote rejected]   refs/pull/95/head -> refs/pull/95/head (deny updating a hidden ref)
 ! [remote rejected]   refs/pull/96/head -> refs/pull/96/head (deny updating a hidden ref)
 ! [remote rejected]   refs/pull/98/head -> refs/pull/98/head (deny updating a hidden ref)
 ! [remote rejected]   refs/pull/99/head -> refs/pull/99/head (deny updating a hidden ref)
error: failed to push some refs to 'git@github.com:PCMSolver/pcmsolver-backup.git'
```

**Comment by robertodr** [comment]
I think it wants to carry over PR information, @bast?

**Comment by bast** [comment]
If we want to backup only branches and tags and all commits, then I think we are done. I browsed https://github.com/PCMSolver/pcmsolver-backup and it looks good.

**Comment by bast** [comment]
I think it's normal that a GitHub rejects such refs. It would completely mess up the issue and PR numbering.

**Comment by robertodr** [comment]
when we're Boost-free (soon, I hope) we should really remove those zip files from history.

**Comment by bast** [comment]
Yes. It's a bit bloated now.

**Comment by robertodr** [comment]
You're very diplomatic in your understatement :grinning:

**Comment by arnfinn** [comment]
I renamed and deleted branches, as we agreed on. Had to update all the open pull requests, since they pointed to release/1.2.Z and that branch was deleted (all the pull requests were closed). Did we have 6 open PRs?

Does everything look OK?

**Comment by robertodr** [comment]
On first look, it does. I think ReadTheDocs didn't get the memo, because I'm getting build failure emails. Can you look into that? Thanks!

**Comment by arnfinn** [comment]
I also protected `release/1.1` and `release/1.2`, but not the way `master` is protected. Instead only admins can push to these branches (no PRs).

**Comment by arnfinn** [comment]
I will look into readthedocs...

**Comment by arnfinn** [comment]
I guess we are done?
